FROM eclipse-temurin:17-jre-focal

EXPOSE 8080

ARG DBMS_PROD
ENV DBMS ${DBMS_PROD}
ARG DB_HOST_PROD
ENV DB_HOST ${DB_HOST_PROD}
ARG DB_PORT_PROD
ENV DB_PORT ${DB_PORT_PROD}
ARG DB_NAME_PROD
ENV DB_NAME ${DB_NAME_PROD}
ARG DB_PASSWORD_PROD
ENV DB_PASSWORD ${DB_PASSWORD_PROD}
ARG DB_USERNAME_PROD
ENV DB_USERNAME ${DB_USERNAME_PROD}}

ADD user-infrastructure/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]