FROM eclipse-temurin:17-jre-focal

EXPOSE 8080

ARG DBMS
ENV DBMS ${DBMS}
ARG DB_HOST
ENV DB_HOST ${DB_HOST}
ARG DB_PORT
ENV DB_PORT ${DB_PORT}
ARG DB_NAME
ENV DB_NAME ${DB_NAME}
ARG DB_PASSWORD
ENV DB_PASSWORD ${DB_PASSWORD}
ARG DB_USERNAME
ENV DB_USERNAME ${DB_USERNAME}

ADD user-infrastructure/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app.jar"]