package com.xquare.authentication.v1authenticationservice.authority.accessmanagement.repositories

import com.xquare.authentication.v1authenticationservice.authority.accessmanagement.UserAccessManagementEntity
import java.util.UUID
import org.springframework.data.repository.reactive.ReactiveCrudRepository
import org.springframework.stereotype.Repository

@Repository
interface UserAccessManagementRepository : ReactiveCrudRepository<UserAccessManagementEntity, UUID>
